# Generated by Django 4.0.1 on 2022-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestronBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('add', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
